# Generated by Django 4.2.30 on 2026-07-01 17:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0005_party_loyalty_points'),
        ('tenants', '0003_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Poori committee ki value (e.g. 600000)', max_digits=14)),
                ('members_count', models.PositiveSmallIntegerField(default=12, help_text='Members / months (usually same)')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('coupon1', models.DecimalField(decimal_places=2, default=Decimal('2000'), max_digits=10)),
                ('coupon2', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=10)),
                ('coupon1_holder', models.CharField(blank=True, max_length=120)),
                ('coupon2_holder', models.CharField(blank=True, max_length=120)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=Decimal('1000'), help_text='Boli minimum itne ke multiple me', max_digits=10)),
                ('late_fee_per_day', models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10)),
                ('bid_day', models.PositiveSmallIntegerField(default=5, help_text='Har month is din boli lagti hai')),
                ('due_day', models.PositiveSmallIntegerField(default=10, help_text='Is din tak payment; baad me late fee')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='committee.committee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.party')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_no', models.PositiveSmallIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('bid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Boli/discount (jitna loss dekar uthaya)', max_digits=14)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('coupon_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('per_head', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='committee.committee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='committee.committeemember')),
            ],
            options={
                'ordering': ['month_no'],
                'unique_together': {('committee', 'month_no')},
            },
        ),
        migrations.CreateModel(
            name='CommitteePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='committee.committeemember')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='committee.committeeround')),
            ],
            options={
                'ordering': ['member_id'],
                'unique_together': {('round', 'member')},
            },
        ),
    ]
