# Generated by Django 4.2.30 on 2026-07-01 17:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_lead'),
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='allow_join',
            field=models.BooleanField(default=True, help_text='Public join link se log apply kar sakte hain'),
        ),
        migrations.AddField(
            model_name='committee',
            name='bidding_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='committee',
            name='open_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Kaunse month ki boli abhi khuli hai', null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='public_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='CommitteeJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='committee.committee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_no', models.PositiveSmallIntegerField()),
                ('bid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Jitna discount/loss dekar uthana chahta hai', max_digits=14)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='committee.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='committee.committeemember')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
            ],
            options={
                'ordering': ['-bid_amount'],
                'unique_together': {('committee', 'month_no', 'member')},
            },
        ),
    ]
