# Generated by Django 5.0.6 on 2026-06-22 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('SALE_RETURN', 'Sale Return'), ('PURCHASE_RETURN', 'Purchase Return')], default='SALE', max_length=20)),
                ('number', models.CharField(blank=True, db_index=True, max_length=30)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_posted', models.BooleanField(default=False, help_text='Stock update ho chuka?')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('company_state_code', models.CharField(blank=True, default='', max_length=2)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='core.godown')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='party.party')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Price per selected unit', max_digits=14)),
                ('price_inclusive_tax', models.BooleanField(default=False, help_text='Rate tax ke saath hai? (with/without tax)')),
                ('disc1_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('disc2_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('disc3_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('margin_type', models.CharField(blank=True, choices=[('AMOUNT', 'Amount'), ('PERCENT', 'Percent')], max_length=10)),
                ('margin_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batch')),
                ('unit', models.ForeignKey(help_text='Kisi bhi unit se billing', on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemvariant')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.voucher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
