# Generated by Django 5.0.6 on 2026-06-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherline',
            name='qty_primary',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Quantity primary unit mein (reporting ke liye)', max_digits=14),
        ),
    ]
