# Generated by Django 5.0.6 on 2026-06-22 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_voucherline_qty_primary'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
    ]
