# Generated by Django 5.0.6 on 2026-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_voucher_organization_voucherline_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('SALE', 'Sale Invoice'), ('PURCHASE', 'Purchase'), ('SALE_RETURN', 'Sale Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('ESTIMATE', 'Estimate / Quotation'), ('DELIVERY_CHALLAN', 'Delivery Challan'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note')], default='SALE', max_length=20),
        ),
    ]
