# Generated by Django 5.0.6 on 2026-06-22 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_voucher_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public share link ke liye (token leak ke bina)'),
        ),
    ]
