# Generated by Django 4.2.30 on 2026-06-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_voucher_share_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('SALE', 'Sale Invoice'), ('PURCHASE', 'Purchase'), ('SALE_RETURN', 'Sale Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('ESTIMATE', 'Estimate / Quotation'), ('PROFORMA', 'Proforma Invoice'), ('SALE_ORDER', 'Sale Order'), ('DELIVERY_CHALLAN', 'Delivery Challan'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note')], default='SALE', max_length=20),
        ),
    ]
