# Generated by Django 4.2.30 on 2026-06-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('billing', '0006_alter_voucher_voucher_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Sharma Ji - Monthly AMC'", max_length=120)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('start_date', models.DateField()),
                ('next_run', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Khaali = chalta rahega', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_post', models.BooleanField(default=True, help_text='Generate ke saath stock bhi post ho')),
                ('generated_count', models.PositiveIntegerField(default=0)),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('source_voucher', models.ForeignKey(help_text='Is invoice ko template ki tarah clone karta hai', on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='billing.voucher')),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
    ]
