# Generated by Django 4.2.30 on 2026-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_recurringinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='cess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='cess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='cess_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional CESS % (e.g. tobacco, auto)', max_digits=6),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='free_qty',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Free quantity (stock se nikalti, charge nahi)', max_digits=14),
        ),
    ]
