# Generated by Django 4.2.30 on 2026-06-22 17:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_voucher_cess_voucherline_cess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='currency',
            field=models.CharField(default='INR', max_length=5),
        ),
        migrations.AddField(
            model_name='voucher',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='1 foreign currency = ? INR', max_digits=12),
        ),
    ]
