# Generated by Django 5.2.15 on 2026-07-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_voucher_currency_voucher_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherline',
            name='description',
            field=models.CharField(blank=True, help_text='Line description / note (invoice par print)', max_length=255),
        ),
    ]
