# Generated by Django 5.2.15 on 2026-07-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_voucherline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='converted_to',
            field=models.ForeignKey(blank=True, help_text='Estimate/Order/Challan ka banaya hua invoice (ek hi baar convert ho)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from', to='billing.voucher'),
        ),
    ]
