# Generated by Django 4.2.30 on 2026-07-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_organization_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_listed', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('kirana', 'Kirana / Grocery'), ('wholesale', 'Wholesale / Distributor'), ('pharmacy', 'Pharmacy / Medical'), ('garment', 'Garment / Textile'), ('hardware', 'Hardware / Sanitary'), ('electronics', 'Electronics / Mobile'), ('restaurant', 'Restaurant / Food supplies'), ('stationery', 'Stationery / Books'), ('cosmetics', 'Cosmetics / General'), ('agri', 'Agri / Seeds / Fertilizer'), ('other', 'Other')], default='wholesale', max_length=30)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('about', models.TextField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('min_order', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to='tenants.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=120)),
                ('from_phone', models.CharField(blank=True, max_length=15)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CLOSED', 'Closed')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_enquiries', to='tenants.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_enquiries', to='tenants.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
