# Generated by Django 5.0.6 on 2026-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_organization_godown_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('RETAIL', 'Retail Shop / Kirana'), ('WHOLESALE', 'Wholesale / Distributor'), ('RESTAURANT', 'Restaurant / Cafe'), ('PHARMACY', 'Pharmacy / Medical'), ('SERVICES', 'Services / Professional'), ('MANUFACTURER', 'Manufacturer'), ('GENERAL', 'General / Other')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='default_item_type',
            field=models.CharField(default='GOODS', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='default_price_inclusive',
            field=models.BooleanField(default=False, help_text='MRP/inclusive billing'),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_barcode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_batch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_godown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_serial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_scheme',
            field=models.CharField(choices=[('REGULAR', 'Regular (GST charge)'), ('COMPOSITION', 'Composition (Bill of Supply)'), ('UNREGISTERED', 'Unregistered / No GST')], default='REGULAR', max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='negative_stock_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state_code',
            field=models.CharField(blank=True, help_text='GST state code (intra/inter-state)', max_length=2),
        ),
        migrations.AddField(
            model_name='company',
            name='terms',
            field=models.TextField(blank=True, help_text='Invoice ke neeche terms & conditions'),
        ),
    ]
