# Generated by Django 5.0.6 on 2026-06-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_business_type_company_default_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calculate_tax_on_mrp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_default_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_exp_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_item_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_manufacturing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_mfg_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_model_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_mrp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_stock_maintenance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_wholesale_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='item_wise_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='item_wise_tax',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='party_wise_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='quantity_decimals',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='company',
            name='sell_type',
            field=models.CharField(default='BOTH', help_text='PRODUCT / SERVICE / BOTH', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='show_low_stock_dialog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='update_sale_price_from_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_api_token',
            field=models.CharField(blank=True, help_text='(Optional) WhatsApp Business Cloud API token — auto-send ke liye', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_business_number',
            field=models.CharField(blank=True, help_text='Aapka WhatsApp number (countrycode ke saath, e.g. 9198...)', max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
