# Generated by Django 5.0.6 on 2026-06-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_calculate_tax_on_mrp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='godown',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['short_code']},
        ),
    ]
