# Generated by Django 4.2.30 on 2026-06-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, help_text='WhatsApp Cloud API Phone Number ID', max_length=40),
        ),
    ]
