# Generated by Django 4.2.30 on 2026-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_whatsapp_phone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='signature',
            field=models.ImageField(blank=True, help_text='Authorised signatory — invoice par print hoga', null=True, upload_to='company_signatures/'),
        ),
    ]
