# Generated by Django 5.0.6 on 2026-06-22 08:09

import apps.party.models
import apps.party.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('legal_name', models.CharField(blank=True, help_text='GST registered legal name', max_length=200)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer (Debtor)'), ('SUPPLIER', 'Supplier (Creditor)'), ('BOTH', 'Both')], default='CUSTOMER', max_length=10)),
                ('gstin', models.CharField(blank=True, max_length=15, validators=[apps.party.validators.validate_gstin], verbose_name='GSTIN')),
                ('pan', models.CharField(blank=True, max_length=10, verbose_name='PAN')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('state_code', models.CharField(blank=True, help_text='GST state code, e.g. 09 (UP)', max_length=2)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('opening_balance_type', models.CharField(choices=[('DR', 'To Receive (Debit)'), ('CR', 'To Pay (Credit)')], default='DR', max_length=2)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to=apps.party.models.party_doc_path)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='party.party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
