# Generated by Django 4.2.30 on 2026-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_party_organization_partydocument_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='party',
            name='group',
            field=models.CharField(blank=True, help_text='Party group (e.g. Dealers, VIP)', max_length=80),
        ),
    ]
