# Generated by Django 4.2.30 on 2026-06-22 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_party_custom_fields_party_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Customer portal public link'),
        ),
    ]
