# Generated by Django 4.2.30 on 2026-06-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('party', '0002_party_organization_partydocument_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash in Hand'), ('BANK', 'Bank Account')], default='BANK', max_length=10)),
                ('account_no', models.CharField(blank=True, max_length=30)),
                ('ifsc', models.CharField(blank=True, max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('upi_id', models.CharField(blank=True, max_length=80)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
            ],
            options={
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lender', models.CharField(max_length=120)),
                ('account_no', models.CharField(blank=True, max_length=40)),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual % rate', max_digits=6)),
                ('tenure_months', models.PositiveIntegerField(default=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cheque_type', models.CharField(choices=[('RECEIVABLE', 'Receivable (customer se)'), ('PAYABLE', 'Payable (supplier ko)')], default='RECEIVABLE', max_length=12)),
                ('cheque_no', models.CharField(max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.party')),
            ],
            options={
                'ordering': ['due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('IN', 'Money In'), ('OUT', 'Money Out')], default='IN', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mode', models.CharField(blank=True, default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashbank.bankaccount')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.party')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
