# Generated by Django 4.2.30 on 2026-06-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0002_expensecategory_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='reconciled',
            field=models.BooleanField(default=False, help_text='Bank statement se match ho gaya?'),
        ),
    ]
