# Generated by Django 5.0.6 on 2026-06-22 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('RECEIPT', 'Receipt (customer se)'), ('PAYMENT', 'Payment (supplier ko)')], default='RECEIPT', max_length=10)),
                ('number', models.CharField(blank=True, db_index=True, max_length=30)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque')], default='CASH', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Cheque/UPI ref no.', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='party.party')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
