# Generated by Django 5.0.6 on 2026-06-22 08:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Item-code prefix, e.g. ELE', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=10, verbose_name='HSN/SAC')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='1 secondary unit = kitne primary unit', max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category')),
                ('primary_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_items', to='core.unit')),
                ('secondary_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_items', to='core.unit')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taxrate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(blank=True, max_length=30)),
                ('colour', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=30)),
                ('item_code', models.CharField(blank=True, max_length=40, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=40, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.item')),
            ],
            options={
                'unique_together': {('item', 'size', 'colour', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_no', models.CharField(max_length=50)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(choices=[('AMOUNT', 'Amount'), ('PERCENT', 'Percent')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.itemvariant')),
            ],
            options={
                'unique_together': {('variant', 'batch_no')},
            },
        ),
        migrations.CreateModel(
            name='ItemUnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_prices', to='inventory.itemvariant')),
            ],
            options={
                'unique_together': {('variant', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='Primary unit mein', max_digits=14)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batch')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.godown')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.itemvariant')),
            ],
            options={
                'unique_together': {('variant', 'godown', 'batch')},
            },
        ),
    ]
