# Generated by Django 5.0.6 on 2026-06-22 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='itemunitprice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='stock',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='item_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name')},
        ),
    ]
