# Generated by Django 5.0.6 on 2026-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_batch_organization_category_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('GOODS', 'Goods (stock tracked)'), ('SERVICE', 'Service (no stock)')], default='GOODS', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Is se kam stock pe low-stock alert (primary unit)', max_digits=12),
        ),
    ]
