# Generated by Django 5.0.6 on 2026-06-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_item_type_item_reorder_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemunitprice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='itemvariant',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['id']},
        ),
    ]
