# Generated by Django 4.2.30 on 2026-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_batch_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
