# Generated by Django 4.2.30 on 2026-06-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('inventory', '0006_pricelist_pricelistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_combo',
            field=models.BooleanField(default=False, help_text='Bundle/BOM — components se bana'),
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('SOLD', 'Sold')], default='IN_STOCK', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='inventory.itemvariant')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('organization', 'serial')},
            },
        ),
        migrations.CreateModel(
            name='ItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, help_text='Ek combo banane mein kitne component (primary unit)', max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='inventory.itemvariant')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.item')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('parent', 'component')},
            },
        ),
    ]
