# Generated by Django 5.2.15 on 2026-07-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_is_combo_serialnumber_itemcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='colour',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='batch',
            name='mfg_date',
            field=models.DateField(blank=True, help_text='Manufacturing date', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='model',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='batch',
            name='size',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Item photo (upload)', null=True, upload_to='item_images/'),
        ),
    ]
