# Generated by Django 4.2.30 on 2026-07-02 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_seed_plans_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('service', models.CharField(max_length=150)),
                ('staff', models.CharField(blank=True, max_length=80)),
                ('start', models.DateTimeField()),
                ('duration_min', models.PositiveSmallIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='BOOKED', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
